site_name: Powertools for AWS Lambda (TypeScript)
site_description: Powertools for AWS Lambda (TypeScript)
site_author: Amazon Web Services
repo_url: https://github.com/aws-powertools/powertools-lambda-typescript
edit_uri: edit/main/docs
site_url: https://docs.powertools.aws.dev/lambda/typescript
watch: [
  docs,
  packages/batch/src,
  examples/snippets/batch,
  packages/commons/src,
  packages/event-handler/src,
  examples/snippets/event-handler,
  packages/idempotency/src,
  examples/snippets/idempotency,
  packages/jmespath/src,
  examples/snippets/jmespath,
  packages/logger/src,
  examples/snippets/logger,
  packages/metrics/src,
  examples/snippets/metrics,
  packages/parameters/src,
  examples/snippets/parameters,
  packages/parser/src,
  examples/snippets/parser,
  packages/tracer/src,
  examples/snippets/tracer,
  packages/validation/src,
  examples/snippets/validation,
]

nav:
  - Homepage:
      - index.md
      - Getting Started:
          - Navigating the toolkit: getting-started/navigating-the-toolkit.md
          - Installation: getting-started/installation.md
          - TypeScript settings: getting-started/typescript-settings.md
          - Lambda layers: getting-started/lambda-layers.md
          - Workshop: https://s12d.com/powertools-for-aws-lambda-workshop" target="_blank
      - Features:
          - features/index.md 
          - features/tracer.md
          - features/logger.md
          - features/metrics.md
          - features/parameters.md
          - features/idempotency.md
          - features/batch.md
          - features/jmespath.md
          - features/parser.md
          - features/validation.md
      - Environment variables: environment-variables.md
      - Upgrade guide: upgrade.md
      - Community Content: we_made_this.md
      - Roadmap: roadmap.md
      - Changelog: changelog.md
  - API reference: api/" target="_blank
  - Processes:
      - Roadmap: roadmap.md
      - Versioning policy: versioning.md
      - Maintainers: maintainers.md
      - Contributing:
          - Development environment: contributing/setup.md
          - Your first contribution: contributing/getting_started.md
          - Conventions: contributing/conventions.md
          - Testing: contributing/testing.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  logo: media/aws-logo-light.svg
  favicon: media/aws-logo-light.svg
  custom_dir: docs/overrides

markdown_extensions:
  - admonition
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
      restrict_base_path: false
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; 2025 Amazon Web Services

plugins:
  - privacy
  - git-revision-date
  - search
  - exclude:
      glob:
        - snippets/node_modules/*
        - snippets/package.json
        - snippets/CHANGELOG.md
  - typedoc:
      source: '.'
      output_dir: 'api'
      tsconfig: 'tsconfig.json'
      options: 'typedoc.json'
      name: 'API Reference'

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/aws-amplify.min.js
  - javascript/extra.js
  - https://docs.powertools.aws.dev/shared/mermaid.min.js

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aws-powertools/powertools-lambda-typescript
    - icon: fontawesome/brands/discord
      link: https://discord.gg/B8zZKbbyET
      name: Join our Discord Server!
  status:
    new: New Utility
