blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/new
    about: Ask a general question about Lambda Powertools
  - name: Join Community Discord Server
    url: https://discord.gg/B8zZKbbyET
    about: "Check out the #typescript channel"