blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aws-powertools/powertools-lambda-typescript/discussions/new
    about: Ask a general question about Powertools for AWS Lambda
  - name: Join Community Discord Server
    url: https://discord.gg/B8zZKbbyET
    about: "Check out the #typescript channel"