name: Auto publish docs to version "develop"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'mkdocs.yml'
      - '.github/workflows/on-docs-change.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.8'
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17.2'
      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install mike==1.1.2 mkdocs-material==8.0.5 mkdocs-git-revision-date-plugin==0.3.1
          npm ci
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Build mkdocs site in 'gh-pages' branch and push
        run: |
          rm -rf site
          VERSION="develop"
          ALIAS="stage"
          mkdocs build
          mike deploy --push --update-aliases "$VERSION" "$ALIAS"
      - name: Build API documentation site 
        run: |
          rm -rf api
          npm run docs-generateApiDoc
      - name: Deploy API documentation site (copy to "gh-pages" branch inside the version folder)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          keep_files: true
          destination_dir: develop/api 