name: Post Release

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      versionNumber:
        required: true
        type: string
        description: "If running this manually please insert a version number that corresponds to the latest published in the GitHub releases (i.e. v1.1.1)"
  # Or triggered as result of a release
  release:
    types: [released]

permissions:
  contents: read

jobs:
  post_release:
    permissions:
      contents: read
      issues: write
      discussions: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.versionNumber }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      - name: Get release version
        run: |
          # The code below does the following:
          # 1. If the workflow was triggered manually, it will use the version number provided by the user
          # 2. If the workflow was triggered by a release, it will use the version number of the release
          if [ -z "$RELEASE_VERSION" ]; then
            export RELEASE_VERSION=$(git describe --tags --abbrev=0)
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Update issues related to release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const post_release = require('.github/scripts/post_release.js')
            await post_release({github, context, core})