name: test-pkg-size
on:
  workflow_dispatch: {}
  push:
    branches:
      - flochaz/pkgSize
# defaults:
#   run:
#     working-directory: packages/metrics
jobs:
  on_push:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
      - name: Package size report
        uses: .github/actions/pkg-size
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
