name: "Close stale issues"

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  check-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has not received a response in 2 weeks. If you still think there is a problem, please leave a comment to avoid the issue from automatically closing."
          close-issue-message: "Greetings! We are closing this issue because it has been open a long time and hasnâ€™t been updated in a while and may not be getting the attention it deserves. We encourage you to check if this is still an issue in the latest release and if you find that this is still a problem, please feel free to comment or reopen the issue."
          # Label applied or removed when an issue becomes stale
          stale-issue-label: status/pending-close-response-required
          remove-stale-when-updated: true
          # Label and close type when a stale issue is finally closed
          close-issue-label: status/rejected
          close-issue-reason: not_planned
          # Exempt any issue that hasn't been triaged yet, or that is clearly labeled
          exempt-issue-labels: triage,status/confirmed,status/blocked,status/on-hold,status/completed
          # Include only issues that were labeled as `need-response` (aka only issues that need a response from the customer)
          only-issue-labels: need-response
          # Settings specific to issues
          days-before-issue-stale: 14
          days-before-issue-close: 7
          # Set to ignore PRs
          days-before-pr-stale: -1
          days-before-pr-close: -1
          # Operations
          operations-per-run: 60
